import JSZip from "jszip";
const $=s=>document.querySelector(s),code=$("#code"),hud=$("#hud"),tree=$("#tree"),tabs=$("#tabs");
let files=new Map(),urls=new Map(),open=[],active=null,last=null,timer;
const norm=p=>String(p||"").replaceAll("\\","/").replace(/^\/+/,"").toLowerCase();
const json=p=>/\.(json|jsonc)$/i.test(p),img=p=>/\.(png|jpg|jpeg|webp|gif)$/i.test(p);
function url(p){p=norm(p);if(urls.has(p))return urls.get(p);let f=files.get(p);if(!f)return null;let u=URL.createObjectURL(f.blob);urls.set(p,u);return u}
function clear(){urls.forEach(URL.revokeObjectURL);urls.clear();files.clear();open=[];active=null}
async function loadZip(file){clear();let z=await JSZip.loadAsync(file);for(let [n,e] of Object.entries(z.files))if(!e.dir)files.set(norm(n),{name:n,blob:await e.async("blob")});$("#meta").textContent=`${file.name} • ${files.size} files`;drawTree();drawTextures();autoOpen()}
function loadFolder(list){clear();for(let f of list)files.set(norm(f.webkitRelativePath||f.name),{name:f.webkitRelativePath||f.name,blob:f});$("#meta").textContent=`Folder • ${files.size} files`;drawTree();drawTextures();autoOpen()}
function autoOpen(){let p=[...files.keys()].find(x=>x.endsWith("hud_screen.json"))||[...files.keys()].find(json);if(p)openFile(p)}
function drawTree(){let q=norm($("#search").value);tree.innerHTML="";let paths=[...files.keys()].filter(p=>!q||p.includes(q)).sort();let seen=new Set();for(let p of paths){let a=p.split("/");for(let i=0;i<a.length;i++){let k=a.slice(0,i+1).join("/")+(i<a.length-1?"/":"");if(seen.has(k))continue;seen.add(k);let d=document.createElement("div");d.className="row "+(i<a.length-1?"dir":"");d.style.paddingLeft=5+i*13+"px";d.textContent=(i<a.length-1?"▸ ":json(p)?"▣ ":img(p)?"▧ ":"• ")+a[i];if(i===a.length-1&&json(p)){d.classList.toggle("active",p===active);d.onclick=()=>openFile(p)}tree.appendChild(d)}}}
function drawTextures(){let g=$("#grid"),q=norm($("#texsearch").value);g.innerHTML="";[...files.keys()].filter(img).filter(p=>!q||p.includes(q)).slice(0,600).forEach(p=>{let d=document.createElement("div");d.className="tex";let im=document.createElement("img");im.src=url(p);let s=document.createElement("small");s.textContent=p;d.append(im,s);g.append(d)})}
async function openFile(p){saveMemory();active=p;if(!open.includes(p))open.push(p);let f=files.get(p);code.value=f.text??await f.blob.text();f.text=code.value;$("#file").textContent=f.name;drawTabs();update()}
function drawTabs(){tabs.innerHTML="";open.forEach(p=>{let d=document.createElement("span");d.className="tab "+(p===active?"active":"");d.textContent=files.get(p)?.name.split("/").pop();d.onclick=()=>openFile(p);tabs.append(d)})}
function saveMemory(){if(active&&files.has(active)){let f=files.get(active);f.text=code.value;f.blob=new Blob([code.value],{type:"application/json"});urls.delete(active)}}
function strip(s){let o="",str=0,esc=0;for(let i=0;i<s.length;i++){let c=s[i],n=s[i+1];if(str){o+=c;if(esc)esc=0;else if(c==="\\")esc=1;else if(c==='"')str=0;continue}if(c==='"'){str=1;o+=c;continue}if(c==="/"&&n==="/"){while(i<s.length&&s[i]!=="\n")i++;o+="\n";continue}o+=c}return o}
function parse(){return JSON.parse(strip(code.value))}
function num(v,parent){if(typeof v==='number')return v;if(Array.isArray(v))return num(v[0],parent);if(typeof v!=="string")return 0;let m=v.match(/^(-?[\d.]+)%$/);if(m)return parent*+m[1]/100;m=v.match(/(-?[\d.]+)px/);return m?+m[1]:parseFloat(v)||0}
function point(a,w,h){return ({top_left:[0,0],top_middle:[w/2,0],top_right:[w,0],middle_left:[0,h/2],center:[w/2,h/2],middle_right:[w,h/2],bottom_left:[0,h],bottom_middle:[w/2,h],bottom_right:[w,h]})[a]||[0,0]}
function box(d,pw,ph){let s=d.size||[0,0],w=num(s[0],pw),h=num(s[1],ph),a=point(d.anchor_from,pw,ph),b=point(d.anchor_to,w,h),o=d.offset||[0,0];return{x:a[0]-b[0]+num(o[0],pw),y:a[1]-b[1]+num(o[1],ph),w,h}}
function texCandidates(t){t=norm(t).replace(/\.png$/,'');return t.startsWith('textures/')?[t,t+'.png']:[t,t+'.png','textures/'+t,'textures/'+t+'.png']}
function findTex(t){for(let p of texCandidates(t))if(files.has(p))return url(p);return null}
function ref(v,defs){if(typeof v!=="string"||!v.includes("@"))return v||{};return defs[v.split("@").pop()]||{}}
function add(parent,d,name,pw,ph,defs){if(!d||typeof d!=="object")return;let e=document.createElement("div"),b=box(d,pw,ph);e.className="node";e.style.cssText=`left:${b.x}px;top:${b.y}px;width:${Math.max(0,b.w)}px;height:${Math.max(0,b.h)}px;z-index:${d.layer||0}`;if(d.type==='image'){e.classList.add('image');let u=findTex(d.texture||'');if(u)e.style.backgroundImage=`url("${u}")`;else{e.classList.add('placeholder');e.textContent=(d.texture||name).split('/').pop()}}else if(d.type==='label'){e.classList.add('text');e.textContent=d.text||name;e.style.fontSize=Math.max(8,num(d.font_size==='small'?11:d.font_size,20)*(+d.font_scale_factor||1))+'px';e.style.textAlign=d.text_alignment||'left'}else if(d.type==='custom'){let n=name.toLowerCase();if(/health|hunger|armor/.test(n)){let k=n.includes('health')?'hp':n.includes('hunger')?'food':'armor';e.className+=' barhp bar'+k;let i=document.createElement('i');i.style.width=($("#"+k).value/20*100)+'%';e.append(i)}}parent.append(e);if(Array.isArray(d.controls))for(let x of d.controls){let k=Object.keys(x)[0];add(e,ref(x[k],defs),k,b.w,b.h,defs)}}
function render(h){hud.innerHTML='';let pw=$("#game").clientWidth,ph=$("#game").clientHeight,defs={...(h||{}),...(h?.hud_content||{})};for(let x of h?.hud_content?.controls||[]){let k=Object.keys(x)[0];add(hud,ref(x[k],defs),k,pw,ph,defs)}if($("#action").value){let e=document.createElement('div');e.className='node text';e.textContent=$("#action").value;e.style.cssText='left:50%;bottom:21%;transform:translateX(-50%);z-index:99;font-size:13px';hud.append(e)}if($("#title").value){let e=document.createElement('div');e.className='node text';e.textContent=$("#title").value;e.style.cssText='left:50%;top:50%;transform:translate(-50%,-50%);z-index:100;font-size:28px';hud.append(e)}}
function update(){let n=code.value.split('\n').length;$("#nums").textContent=Array.from({length:n},(_,i)=>i+1).join('\n');try{last=parse();render(last);$("#status").textContent='● LIVE • valid JSON';$("#status").className='ok'}catch(e){$("#status").textContent='● '+e.message;$("#status").className='err'}}
code.oninput=()=>{saveMemory();clearTimeout(timer);timer=setTimeout(update,100)};code.onscroll=()=>$("#nums").scrollTop=code.scrollTop;$("#search").oninput=drawTree;$("#texsearch").oninput=drawTextures;$("#format").onclick=()=>{try{code.value=JSON.stringify(parse(),null,2);saveMemory();update()}catch{}};$("#save").onclick=saveMemory;
$("#zip").onchange=e=>e.target.files[0]&&loadZip(e.target.files[0]);$("#folder").onchange=e=>e.target.files?.length&&loadFolder(e.target.files);
$("#export").onclick=async()=>{saveMemory();if(!files.size)return alert('Load a resource pack first.');let z=new JSZip();for(let [p,f] of files)z.file(f.name,f.text??f.blob);let b=await z.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='MCBE_UI_Studio_pack.zip';a.click()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('aside section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$("#"+b.dataset.tab).classList.add('active')});document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$("#stage").className='stage '+b.dataset.device});$("#full").onclick=()=>$("#game").requestFullscreen?.();['title','action','hp','food','armor'].forEach(id=>$("#"+id).oninput=()=>last&&render(last));
